import { useEffect,useState } from "react";
import { AlertTriangle, ArrowRight, Clock3, LogOut, RefreshCw } from "lucide-react";
import BrandHeader from "./BrandHeader";
import { getDoctorQueue } from "../lib/consultations";
import { supabase } from "../lib/supabase/client";

export default function DoctorQueueScreen({ onOpen,onLogout }){
 const [items,setItems]=useState([]);const [state,setState]=useState("loading");const [error,setError]=useState("");
 const load=async()=>{setState("loading");setError("");try{setItems(await getDoctorQueue());setState("ready");}catch(e){setError(e.message);setState("error");}};useEffect(()=>{load();},[]);
 return <main className="min-h-[100dvh] bg-[#edf0eb]"><BrandHeader compact/><section className="mx-auto max-w-[1180px] px-5 pb-12 md:px-10"><div className="flex flex-col gap-5 border-b border-[#103f33] pb-7 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-5xl font-black tracking-[-.04em] text-[#103f33]">Consultation queue</h1><p className="mt-3 text-lg font-semibold text-[#527269]">Oldest patient first · pending and flagged reviews</p></div><div className="flex gap-2"><button onClick={load} className="flex min-h-12 items-center gap-2 rounded-[14px] bg-white px-4 font-black"><RefreshCw/>Refresh</button><button onClick={async()=>{await supabase?.auth.signOut();onLogout();}} className="flex min-h-12 items-center gap-2 rounded-[14px] bg-[#103f33] px-4 font-black text-white"><LogOut/>Sign out</button></div></div>{error&&<div role="alert" className="mt-6 rounded-[14px] bg-[#fff0e8] p-4 font-bold text-[#8b311f]">{error}</div>}<div className="mt-6 overflow-hidden rounded-[16px] bg-white shadow-[0_16px_40px_rgba(16,63,51,.08)]">{state==="loading"?<p className="p-8 text-lg font-black">Loading consultations…</p>:!items.length?<div className="p-12 text-center"><Clock3 className="mx-auto text-[#1d6e59]" size={50}/><h2 className="mt-5 text-3xl font-black">Queue is clear</h2><p className="mt-2 font-semibold text-[#527269]">New patient submissions will appear here.</p></div>:items.map((item)=><button key={item.id} onClick={()=>onOpen(item.id)} className="grid w-full gap-3 border-b border-[#d8e1dc] p-5 text-left last:border-0 hover:bg-[#f7f8f5] md:grid-cols-[1fr_1.3fr_auto] md:items-center"><div><strong className="text-xl text-[#103f33]">{item.patients?.name||"Unknown patient"}</strong><span className="mt-1 flex items-center gap-2 text-sm font-bold text-[#527269]"><Clock3 size={16}/>{new Date(item.created_at).toLocaleString()}</span></div><div><span className="font-extrabold text-[#36564e]">{item.structured_record?.chief_complaints?.join(", ")||"No chief complaint"}</span>{item.red_flag_status?.emergency&&<span className="mt-2 flex items-center gap-2 font-black text-[#8e2f24]"><AlertTriangle size={18}/>Urgent red flag</span>}</div><ArrowRight className="text-[#1d6e59]"/></button>)}</div></section></main>;
}
