import { useState } from "react";
import { MailCheck, Stethoscope, UserPlus } from "lucide-react";
import BrandHeader from "./BrandHeader";
import { supabase } from "../lib/supabase/client";

export default function DoctorSignupScreen({ onSignIn }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [sent,setSent]=useState(false);
  // The account is created here, but it can see nothing until the doctor
  // confirms their email, completes onboarding, and an administrator approves.
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError("");try{if(!supabase)throw new Error("Supabase doctor authentication is not configured.");if(password.length<8)throw new Error("Use a password of at least 8 characters.");const {data,error:authError}=await supabase.auth.signUp({email,password});if(authError)throw authError;if(data.session){onSignIn();return;}setSent(true);}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <main className="min-h-[100dvh] bg-[#edf0eb]"><BrandHeader compact/><section className="mx-auto grid max-w-[1120px] gap-6 px-5 pb-12 md:grid-cols-[.9fr_1.1fr] md:px-10"><div className="rounded-[16px] bg-[#103f33] p-8 text-white md:p-10"><Stethoscope size={52} className="text-[#f2d533]"/><h1 className="mt-8 text-6xl font-black leading-[.94] tracking-[-.04em]">Apply for access</h1><p className="mt-6 text-xl font-semibold leading-relaxed text-[#b8d5cc]">Create your sign-in, tell us your medical registration number, and an IleraPoint administrator will review your application. No patient record is visible until you are approved.</p></div>
    {sent
      ? <div className="rounded-[16px] bg-white p-7 shadow-[0_16px_40px_rgba(16,63,51,.08)] md:p-10"><MailCheck size={34} className="text-[#1d6e59]"/><h2 className="mt-5 text-3xl font-black">Confirm your email</h2><p className="mt-4 text-lg font-semibold leading-relaxed text-[#527269]">We sent a confirmation link to <strong className="text-[#103f33]">{email}</strong>. Open it, then sign in to finish your application.</p><button onClick={onSignIn} className="mt-7 min-h-16 w-full rounded-[14px] bg-[#103f33] px-6 text-lg font-black text-white">Go to sign in</button></div>
      : <form onSubmit={submit} className="rounded-[16px] bg-white p-7 shadow-[0_16px_40px_rgba(16,63,51,.08)] md:p-10"><UserPlus size={34} className="text-[#1d6e59]"/><h2 className="mt-5 text-3xl font-black">Create your sign-in</h2><label className="mt-7 block font-black">Work email<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="mt-2 min-h-14 w-full rounded-[14px] bg-[#f1f3ee] px-4"/></label><label className="mt-5 block font-black">Password<input required type="password" minLength={8} value={password} onChange={(e)=>setPassword(e.target.value)} className="mt-2 min-h-14 w-full rounded-[14px] bg-[#f1f3ee] px-4"/><span className="mt-2 block text-sm font-bold text-[#527269]">At least 8 characters.</span></label>{error&&<div role="alert" className="mt-5 rounded-[14px] bg-[#fff0e8] p-4 font-bold text-[#8b311f]">{error}</div>}<button disabled={busy} className="mt-7 min-h-16 w-full rounded-[14px] bg-[#103f33] px-6 text-lg font-black text-white">{busy?"Creating your account…":"Create account"}</button><button type="button" onClick={onSignIn} className="mt-4 min-h-12 w-full font-black text-[#155944] underline decoration-2 underline-offset-4">I already have an account</button></form>}
  </section></main>;
}
