import { useState } from "react";
import { LockKeyhole, Stethoscope } from "lucide-react";
import BrandHeader from "./BrandHeader";
import { supabase } from "../lib/supabase/client";

export default function DoctorLoginScreen({ onSignedIn }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError("");try{if(!supabase)throw new Error("Supabase doctor authentication is not configured.");const {error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError)throw authError;onSignedIn();}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <main className="min-h-[100dvh] bg-[#edf0eb]"><BrandHeader compact/><section className="mx-auto grid max-w-[1120px] gap-6 px-5 pb-12 md:grid-cols-[.9fr_1.1fr] md:px-10"><div className="rounded-[16px] bg-[#103f33] p-8 text-white md:p-10"><Stethoscope size={52} className="text-[#f2d533]"/><h1 className="mt-8 text-6xl font-black leading-[.94] tracking-[-.04em]">Doctor workspace</h1><p className="mt-6 text-xl font-semibold leading-relaxed text-[#b8d5cc]">Review patient-reported intake, watch consented visit recordings, and issue a prescription after your own assessment.</p></div><form onSubmit={submit} className="rounded-[16px] bg-white p-7 shadow-[0_16px_40px_rgba(16,63,51,.08)] md:p-10"><LockKeyhole size={34} className="text-[#1d6e59]"/><h2 className="mt-5 text-3xl font-black">Sign in securely</h2><label className="mt-7 block font-black">Email<input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} className="mt-2 min-h-14 w-full rounded-[14px] bg-[#f1f3ee] px-4"/></label><label className="mt-5 block font-black">Password<input required type="password" value={password} onChange={(e)=>setPassword(e.target.value)} className="mt-2 min-h-14 w-full rounded-[14px] bg-[#f1f3ee] px-4"/></label>{error&&<div role="alert" className="mt-5 rounded-[14px] bg-[#fff0e8] p-4 font-bold text-[#8b311f]">{error}</div>}<button disabled={busy} className="mt-7 min-h-16 w-full rounded-[14px] bg-[#103f33] px-6 text-lg font-black text-white">{busy?"Signing in…":"Open consultation queue"}</button></form></section></main>;
}
