import { CameraOff, Check, FileCheck2, LockKeyhole, Mic, Video } from "lucide-react";
import { useState } from "react";
import BrandHeader from "./BrandHeader";
import { CONSENT_NOTICE_VERSION, privacyCopy } from "../lib/privacyCopy";

export default function VideoConsentScreen({ patient, language = "en", busy, error, onChoice }) {
  const [researchReuse, setResearchReuse] = useState(false);
  const words = privacyCopy(language);
  const choose = (videoRecording) => onChoice({ audioProcessing: true, videoRecording, researchReuse, noticeVersion: CONSENT_NOTICE_VERSION });

  return <main className="kiosk-shell min-h-[100dvh]"><BrandHeader compact /><section className="relative z-10 mx-auto max-w-5xl px-5 pb-12 md:px-10"><div className="grid gap-8 rounded-[16px] bg-[#103f33] p-7 text-white shadow-[0_18px_45px_rgba(16,63,51,.12)] md:grid-cols-[.82fr_1.18fr] md:p-10"><div><FileCheck2 size={54} className="text-[#f2d533]" aria-hidden="true"/><h1 className="mt-7 text-balance text-[clamp(2.6rem,5vw,4.5rem)] font-black leading-[.98] tracking-[-.04em]">{words.title}</h1><p className="mt-5 text-xl font-semibold text-[#b8d5cc]">{patient.name}, {words.intro}</p><p className="mt-7 rounded-[14px] bg-white/10 p-4 font-bold leading-relaxed text-[#dcebe6]">{words.quality}</p></div><div><div className="space-y-5"><section aria-labelledby="voice-consent-heading"><div className="flex gap-3"><Mic className="mt-1 shrink-0 text-[#f2d533]" aria-hidden="true"/><div><h2 id="voice-consent-heading" className="text-xl font-black">{words.voice}</h2><p className="mt-1 font-semibold leading-relaxed text-[#dcebe6]">{words.voiceBody}</p></div></div></section><section aria-labelledby="video-consent-heading"><div className="flex gap-3"><Video className="mt-1 shrink-0 text-[#f2d533]" aria-hidden="true"/><div><h2 id="video-consent-heading" className="text-xl font-black">{words.video}</h2><p className="mt-1 font-semibold leading-relaxed text-[#dcebe6]">{words.videoBody}</p></div></div></section><div className="flex gap-3"><LockKeyhole className="mt-1 shrink-0 text-[#f2d533]" aria-hidden="true"/><p className="font-semibold leading-relaxed text-[#dcebe6]">{words.privacy}</p></div></div><label className="mt-7 flex cursor-pointer gap-3 rounded-[14px] bg-white/10 p-4"><input type="checkbox" checked={researchReuse} onChange={(event) => setResearchReuse(event.target.checked)} className="mt-1 size-6 shrink-0 accent-[#f2d533]"/><span className="font-bold leading-relaxed">{words.research}</span></label><div className="mt-7 grid gap-3"><button disabled={busy} onClick={() => choose(true)} className="flex min-h-16 items-center justify-center gap-3 rounded-[14px] bg-[#f2d533] px-6 text-lg font-black text-[#103f33] disabled:opacity-60"><Check aria-hidden="true"/>{busy ? "Starting…" : words.withVideo}</button><button disabled={busy} onClick={() => choose(false)} className="flex min-h-16 items-center justify-center gap-3 rounded-[14px] bg-white/10 px-6 text-lg font-black text-white disabled:opacity-60"><CameraOff aria-hidden="true"/>{words.voiceOnly}</button></div><p className="mt-4 text-sm font-bold text-[#b8d5cc]">{words.version}: {CONSENT_NOTICE_VERSION}</p>{error && <div role="alert" className="mt-5 rounded-[14px] bg-[#fff0e8] p-4 font-bold text-[#8b311f]">{error}</div>}</div></div></section></main>;
}
